version: "3.7"

services:
  doc:
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - "3002:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doc.rule=Host(`documentation.ekylibre.com`)"
      - "traefik.http.routers.doc.tls=true"
      - "traefik.http.routers.doc.entrypoints=websecure"
      - "traefik.http.routers.doc.tls.certresolver=myresolver"
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      - proxy_web

networks:
  proxy_web:
    external: true
